update by 航
project-trans/FtM-wiki pull request #4
Opened 2023-10-22 12:43 UTC by GehangMa

2023-10-24 06:37 UTC, Cryolitia requested changes
是否考虑维护 tfsci.ftm.wiki 来存放 （至少目前）FtM 相关的药品说明书

2023-10-24 06:37 UTC, Cryolitia commented on content/hrt/hrt-references.md
> +**HRT效果注意事项(通用）：**
需要注意的是，对于Markdown来说，必须两行之间空一行，或在上一行结尾附加两个空格（不建议），否则两行会在渲染时连接成一行

2023-10-24 06:56 UTC, GehangMa commented on content/hrt/hrt-references.md
> +**HRT效果注意事项(通用）：**
收到，我稍后把说明书上传。

2023-10-24 07:19 UTC, Cryolitia commented on content/hrt/hrt-confirmed.md
> +注：上海瑞金医生可能开具大量检查，费用较高并无法一次查完。瑞金医院睾酮长期缺药，只能提供GnRH类似物，但医生会在病历上备注「建议行雄激素治疗」以便在其他医院「如上海一院等需要hrt处方的医院」配药。
```suggestion
注：上海瑞金医生可能开具大量检查，费用较高并无法一次查完。瑞金医院睾酮长期缺药，只能提供GnRH类似物，但医生会在病历上备注「建议行雄激素治疗」以便在其他医院「如上海一院等需要 HRT 处方的医院」配药。
```

其实这个可以调整一下参照隔壁写到综述里面：https://github.com/project-trans/MtF-wiki/blob/master/content/zh-cn/docs/hrt/hrt-res-overview.md?plain=1#L17

2023-10-24 07:45 UTC, Cryolitia approved these changes

2023-10-24 08:39 UTC, GehangMa commented
> 是否考虑维护 tfsci.ftm.wiki 来存放 （至少目前）FtM 相关的药品说明书

可以，最近有点忙，可能更新比较缓慢

2023-10-25 02:48 UTC, Cryolitia requested changes

2023-10-25 02:48 UTC, Cryolitia commented on content/hrt/_index.md
> +然而，**由于FtM的HRT药物管制比较严格，并不是所有医院药房都有十一酸睾酮药物的库存**
```suggestion
然而，**由于 FtM 的 HRT 药物管制比较严格，并不是所有医院药房都有十一酸睾酮药物的库存**
```

2023-10-25 02:48 UTC, Cryolitia commented on content/hrt/_index.md
> +已持有更高级别医院或本院更高级别医生开具的HRT相关病历或HRT处方的跨性别者可去普通门诊继续开具处方。
```suggestion
已持有更高级别医院或本院更高级别医生开具的 HRT 相关病历或 HRT 处方的跨性别者可去普通门诊继续开具处方。
```

2023-10-25 02:48 UTC, Cryolitia commented on content/hrt/_index.md
> +如未满16岁并希望先停止青春期与第二性征发育再采取HRT治疗，请查阅「GnRH类似物」内容。
```suggestion
如未满16岁并希望先停止青春期与第二性征发育再采取HRT治疗，请查阅「GnRH 类似物」内容。
```

2023-10-25 02:48 UTC, Cryolitia commented on content/hrt/hrt-overview.md
> +在大陆地区，对大部分16岁以下的跨性别青少年，主要开展「GnRH类似物治疗」停止第二性征发育，同时也给予未成年跨性别者一定缓冲的时间。
```suggestion
在大陆地区，对大部分16岁以下的跨性别青少年，主要开展「GnRH 类似物治疗」停止第二性征发育，同时也给予未成年跨性别者一定缓冲的时间。
```

2023-10-25 02:48 UTC, Cryolitia commented on content/hrt/hrt-overview.md
> +据大陆地区目前规定，**未成年跨性别者进行正规GnRH类似物治疗或激素治疗均需要家长的同意**。
这个规定有明确有法律效力的文件吗，如果没有的话就改成下述：

```suggestion
在大陆几乎所有医院，**未成年跨性别者进行正规 GnRH 类似物治疗或激素治疗均需要家长的同意**。
```

2023-10-25 03:17 UTC, GehangMa commented on content/hrt/hrt-overview.md
> +据大陆地区目前规定，**未成年跨性别者进行正规GnRH类似物治疗或激素治疗均需要家长的同意**。
据查证，国家仅对手术事宜有明文法律文件规定，HRT与GnRH年龄规定暂未列出。此「hrt年龄限制」信息来源本人就诊时医生口头所述。感谢指正。

2023-10-25 03:40 UTC, Cryolitia approved these changes
有第二个人approve就立刻合并；距离最后一次活动超过7天也将合并

2023-11-05 10:08 UTC, merged